FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /image-builder

# restore packages before copying entire source - provides optimizations when rebuilding
COPY *.csproj ./
COPY NuGet.config ./
RUN dotnet restore -r win7-x64

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out -r win7-x64


# build runtime image
FROM microsoft/nanoserver
WORKDIR /image-builder
COPY --from=build-env /image-builder/out ./
