parameters:
  name: null
  pool: {}
  pushImages: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  workspace:
    clean: all
  steps:
    - ${{ if eq(parameters.pushImages, 'true') }}:
      - script: docker login -u $(acr.userName) -p $(BotAccount-dotnet-docker-acr-bot-password) $(acr.server)
        displayName: Docker Login
      - script: >
        echo "##vso[task.setvariable variable=buildParameters]
        -DockerRepo $(acr.server)/public/dotnet-buildtools/image-builder
        -PushImages
        -CleanupDocker"
        displayName: Set Build Parameters
    - ${{ if eq(parameters.pushImages, 'false') }}:
      - script: >
        echo "##vso[task.setvariable variable=buildParameters]
        -CleanupDocker"
        displayName: Set Build Parameters
    - powershell: >
        Microsoft.DotNet.ImageBuilder/build.ps1 ${{ parameters.buildParameters }}
      displayName: Build and Publish ImageBuilder
    - ${{ if eq(parameters.pushImages, 'true') }}:
      - script: docker logout
        displayName: Docker Logout
        condition: always()
        continueOnError: true
