parameters:
  publishImages: false

jobs:
- job: Initialize
  pool:
    name: Hosted Windows Container
  steps:
  - powershell: write-host "##vso[task.setvariable variable=timestamp;isOutput=true]$(Get-Date -Format yyyyMMddHHmmss)"
    displayName: Define Timestamp Variable
    name: GenerateTimestamp
- template: build-image-builder-image.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    publishImages: ${{ parameters.publishImages }}
- template: build-image-builder-image.yml
  parameters:
    name: Windows
    pool: Hosted Windows Container
    publishImages: ${{ parameters.publishImages }}
