<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Explicit Nullable setting required for Docker builds from src/ context (won't see root Directory.Build.props).
         Tracking issue for fixing context directory: https://github.com/dotnet/docker-tools/issues/1592 -->
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <SignAssembly>false</SignAssembly>
    <TestRunnerName>MSTest</TestRunnerName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ImageBuilder/Microsoft.DotNet.ImageBuilder.csproj" />
  </ItemGroup>

</Project>
