trigger:
  batch: true
  branches:
    include:
    - master
pr: none

variables:
- group: DotNet-Docker-Common
- group: DotNet-Docker-Secrets

jobs:
- template: jobs/build-image-builder.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    pushImages: true
- template: jobs/build-image-builder.yml
  parameters:
    name: Windows
    pool: Hosted Windows Container
    pushImages: true
