trigger:
  batch: true
  branches:
    include:
    - master
variables:
- group: DotNet-Docker-Common
- group: DotNet-Docker-Secrets

jobs:
- template: jobs/build-image-builder.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
- template: jobs/build-image-builder.yml
  parameters:
    name: Windows
    pool:
      name: DotNetCore-Infra
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
