pr: none
trigger: none

jobs:
- job: ValidateRemoteDockerConfig
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: DotNetCore-Docker-Public
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      name: DotNetCore-Docker
    demands:
    - agent.os -equals linux
    - agent.name -equals $(agentName)
  workspace:
    clean: all
  variables:
    remoteDockerRunCmd:
      docker run
      --rm
      --entrypoint docker
      -v /var/run/docker.sock:/var/run/docker.sock
      -v $(DOCKER_CERT_PATH):/docker-certs
      -e DOCKER_CERT_PATH=/docker-certs
      -e DOCKER_TLS_VERIFY=1
      -e DOCKER_HOST=tcp://$(DOCKER_HOST_IP):2376
      $(imageNames.imageBuilder.linux)
    imageNames.imageBuilder.linux: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-docker-testrunner-63f2145-20184325094343
  steps:
  - script: docker pull $(imageNames.imageBuilder.linux)
    displayName: Pull ImageBuilder
  - script: $(remoteDockerRunCmd) info
    displayName: Validate Remote Docker Daemon Reachability
  - script: |
      if [[ "$(DOCKER_CERT_PATH)" == *"humw"* ]]; then
        echo "##vso[task.setvariable variable=imageNames.ping]mcr.microsoft.com/windows/nanoserver:1809-arm32v7"
        echo "##vso[task.setvariable variable=customPingArgs]"
      else
        echo "##vso[task.setvariable variable=imageNames.ping]arm32v7/debian:stretch"
        echo "##vso[task.setvariable variable=customPingArgs]-c 3"
      fi
    displayName: Define OS Variables
  - script: $(remoteDockerRunCmd) pull $(imageNames.ping)
    displayName: Pull Ping Image
  - script: $(remoteDockerRunCmd) run --rm $(imageNames.ping) ping $(customPingArgs) www.github.com
    displayName: Validate Remote Docker Daemon Container Network Access
