trigger: none
pr: none

parameters:
- name: dataFile
  displayName: Relative path to EOL annotations data file (e.g. eol-3.1.json for file in root of the branch)
  type: string

variables:
- template: templates/variables/image-builder.yml
- name: publishEolAnnotations
  value: true
- name: dryRunArg
  value: ""

extends:
  template: /eng/docker-tools/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(publish.serviceConnectionName)
    - name: $(marStatus.serviceConnectionName)
    stages:
    - stage: eolAnnotate
      displayName: Annotate EOL images
      dependsOn: []
      jobs:
      - job: AnnotateImages
        displayName: Annotate EOL Images
        steps:
        - template: /eng/docker-tools/templates/steps/init-common.yml@self
          parameters:
            dockerClientOS: linux
        - template: /eng/docker-tools/templates/steps/annotate-eol-digests.yml@self
          parameters:
            dataFile: /repo/${{ parameters.dataFile }}
