# This pipelines builds all projects in the repository outside of Dockerfiles so that the artifacts
# can be scanned by SDL steps.  SDL steps do not scan artifacts that are built within Dockerfiles.
trigger:
  branches:
    include:
    - main
pr: none

variables:
- template: /eng/pipelines/templates/variables/common.yml@self
  parameters:
    skipComponentGovernanceDetectionValue: false
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage:
      displayName: CG Detection
      jobs:
      - template: /eng/common/templates/jobs/cg-build-projects.yml@self
