trigger: none
pr: none

schedules:
- cron: "0 0,4,8,12,16,20 * * *"
  displayName: Daily build
  branches:
    include:
    - main
  always: true

variables:
- template: templates/variables/common.yml

jobs:
- template: templates/jobs/check-base-image-updates.yml
  parameters:
    jobName: Build
    subscriptionsPath: eng/check-base-image-subscriptions.json
