trigger: none
pr: none

schedules:
- cron: "0 0,4,8,12,16,20 * * *"
  displayName: Daily build
  branches:
    include:
    - main
  always: true

variables:
- template: templates/variables/common.yml

jobs:
- template: templates/jobs/check-base-image-updates.yml
  parameters:
    jobName: CheckBaseImages
    subscriptionsPath: eng/check-base-image-subscriptions.json
- template: templates/jobs/check-base-image-updates.yml
  parameters:
    jobName: CheckBaseImages_BuildTools
    subscriptionsPath: eng/check-base-image-subscriptions-buildtools.json
    customGetStaleImagesArgs: --base-override-regex '^((centos|debian|fedora|ubuntu):.+)' --base-override-sub '$(overrideRegistry)/$1'
