trigger: none
pr: none

schedules:
- cron: "0 0,4,8,12,16,20 * * *"
  displayName: Daily build
  branches:
    include:
    - main
  always: true

variables:
- template: templates/variables/common.yml

jobs:
- template: templates/jobs/check-base-image-updates.yml
  parameters:
    jobName: Build
    subscriptionsPath: eng/check-base-image-subscriptions.json
    customGetStaleImagesArgs: --base-override-regex '.*\/(ubuntu:.+)' --base-override-sub 'ubuntu.azurecr.io/$1'
# Run a separate job for a different set of subscriptions that's configured to not use the base override
# See https://github.com/dotnet/docker-tools/pull/1038
- template: templates/jobs/check-base-image-updates.yml
  parameters:
    jobName: Build2
    subscriptionsPath: eng/check-base-image-subscriptions2.json
