trigger: none
pr: none

schedules:
- cron: "0 5 * * *"
  displayName: Nightly build
  branches:
    include:
    - main
  always: true

variables:
- template: templates/variables/common.yml

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(clean.serviceConnectionName)
    stages:
    - stage: Build
      dependsOn: []
      jobs:
      - job: Build
        pool:
          vmImage: $(defaultLinuxAmd64PoolImage)
        steps:
        - template: /eng/common/templates/steps/init-docker-linux.yml@self
        - template: /eng/common/templates/steps/clean-acr-images.yml@self
          parameters:
            internalProjectName: ${{ variables.internalProjectName }}
            repo: "build-staging/*"
            subscription: $(acr-staging.subscription)
            resourceGroup: $(acr-staging.resourceGroup)
            acr: $(acr-staging.server)
            action: delete
            age: 15
        - template: /eng/common/templates/steps/clean-acr-images.yml@self
          parameters:
            internalProjectName: ${{ variables.internalProjectName }}
            repo: "public/dotnet/*"
            subscription: $(acr.subscription)
            resourceGroup: $(acr.resourceGroup)
            acr: $(acr.server)
            action: pruneEol
            age: 15
        - template: /eng/common/templates/steps/clean-acr-images.yml@self
          parameters:
            internalProjectName: ${{ variables.internalProjectName }}
            repo: "test/*"
            subscription: $(acr.subscription)
            resourceGroup: $(acr.resourceGroup)
            acr: $(acr.server)
            action: pruneAll
            age: 7
        - template: /eng/common/templates/steps/clean-acr-images.yml@self
          parameters:
            internalProjectName: ${{ variables.internalProjectName }}
            repo: "public/dotnet-buildtools/*"
            subscription: $(acr.subscription)
            resourceGroup: $(acr.resourceGroup)
            acr: $(acr.server)
            action: pruneEol
            age: 15
            customArgs: --exclude $(excludedBuildToolsPrereqsImage)
        # Disabled due to https://github.com/dotnet/docker-tools/issues/797
        # - template: ../common/templates/steps/clean-acr-images.yml
        #   parameters:
        #     repo: "mirror/*"
        #     subscription: $(acr-staging.subscription)
        #     resourceGroup: $(acr-staging.resourceGroup)
        #     arc: $(acr-staging.server)
        #     action: pruneDangling
        #     age: 0
