trigger: none
pr: none

variables:
- group: DotNet-Docker-Common
- group: DotNet-Docker-Secrets

jobs:
- job: Build
  pool: Hosted Ubuntu 1604
  steps:
  - powershell: >
      $(Build.Repository.LocalPath)/eng/Invoke-AcrCleanup.ps1 `
      -RegistryName $(acr.server) `
      -SubscriptionId $(acr.subscription) `
      -ServicePrincipalName $(acr.servicePrincipalName) `
      -ServicePrincipalPassword $(app-dotnetdockerbuild-client-secret) `
      -ServicePrincipalTenant $(acr.servicePrincipalTenant)
    displayName: Cleanup ACR Images
