trigger: none
pr: none

variables:
- template: templates/variables/common.yml

jobs:
- job: Build
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - template: ../common/templates/steps/init-docker-linux.yml
  - template: ../common/templates/steps/clean-acr-images.yml
    parameters:
      internalProjectName: ${{ variables.internalProjectName }}
      repo: $(repo)
      subscription: $(acr.subscription)
      resourceGroup: $(acr.resourceGroup)
      acr: $(acr.server)
      action: $(action)
      age: $(age)
      customArgs: $(customArgs)
