trigger: none
pr: none

schedules:
- cron: "0 5 * * *"
  displayName: Nightly build
  branches:
    include:
    - master

variables:
- template: ../common/templates/variables/common.yml

jobs:
- job: Build
  pool: Hosted Ubuntu 1604
  steps:
  - template: ../common/templates/steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) cleanAcrImages
      $(acr.servicePrincipalName)
      $(app-dotnetdockerbuild-client-secret)
      $(acr.servicePrincipalTenant)
      $(acr.subscription)
      $(acr.resourceGroup)
      $(acr.server)
    displayName: Clean ACR Images
  - template: ../common/templates/steps/cleanup-docker-linux.yml
