trigger: none
pr: none

schedules:
- cron: "0 5 * * *"
  displayName: Nightly build
  branches:
    include:
    - master

variables:
- template: ../common/templates/variables/common.yml

jobs:
- job: Build
  pool: Hosted Ubuntu 1604
  steps:
  - template: ../common/templates/steps/init-docker-linux.yml
  - template: templates/steps/clean-acr-images.yml
    parameters:
      repo: "build-staging/*"
      action: delete
      age: 15
  - template: templates/steps/clean-acr-images.yml
    parameters:
      repo: "public/dotnet/*nightly/*"
      action: pruneDangling
      age: 30
  - template: templates/steps/clean-acr-images.yml
    parameters:
      repo: "test/*"
      action: pruneAll
      age: 7
  - template: ../common/templates/steps/cleanup-docker-linux.yml
