trigger: none
pr: none

parameters:
- name: enableDryRun
  displayName: Enable Dry Run
  default: false
  type: boolean

variables:
- template: /eng/pipelines/templates/variables/common.yml@self
- name: publishEolAnnotations
  value: false
  readonly: true

extends:
  template: /eng/docker-tools/templates/1es.yml@self
  parameters:
    stages:
    - template: /eng/docker-tools/templates/stages/setup-service-connections.yml@self
      parameters:
        serviceConnections:
        # For image removal
        - name: $(clean-test.serviceConnectionName)
        # For EOL annotations
        - name: $(build-test.serviceConnectionName)
        - name: $(public-mirror.serviceConnectionName)
    - template: /eng/docker-tools/templates/stages/dotnet/publish-config-nonprod.yml@self
      parameters:
        stagesTemplate: /eng/pipelines/templates/stages/cleanup-acr-images.yml@self
        stagesTemplateParameters:
          enableDryRun: ${{ parameters.enableDryRun }}
