trigger: none
pr: none

variables:
- template: templates/variables/common.yml

jobs:
- job: Build
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - template: ../common/templates/steps/init-docker-linux.yml
  - template: templates/steps/clean-acr-images.yml
    parameters:
      repo: $(repo)
      action: $(action)
      age: $(age)
      customArgs: $(customArgs)
  - template: ../common/templates/steps/cleanup-docker-linux.yml
