# This pipeline builds all packages produced by this repo.
#
# Use this pipeline for public PR validation builds only. For internal PR
# validation, use the unofficial version of the pipeline.
#
# Keep this pipeline in sync with:
# - eng/pipelines/docker-tools-packages-official.yml
# - eng/pipelines/docker-tools-packages-unofficial.yml

trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/common/*
    - eng/pipelines/*
    - src/ImageBuilder.Models/*
    - Directory.Build.props
    - Directory.Build.targets
    - global.json

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-amd64

variables:
- template: /eng/pipelines/templates/variables/packages-build-pools.yml@self

stages:
- stage: build
  displayName: Build and publish packages
  jobs:
  - template: /eng/pipelines/templates/jobs/build-and-publish-packages.yml@self
    parameters:
      containerResource: LinuxContainer
      enablePublish: false
