trigger: none
pr:
  branches:
    include:
    - main

variables:
  - template: /eng/pipelines/templates/variables/packages-common.yml@self

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-amd64

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml@self
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      enableTelemetry: true

      jobs:
      - job: Windows_NT
        pool:
          name: $(PoolProvider)
          demands: ImageOverride -equals $(WindowsAmd64BuildImage)
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              # PRs or external builds are not signed.
              _SignType: test
            Build_Debug:
              _BuildConfig: Debug
              _SignType: test
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig)
            -prepareMachine
          displayName: Windows Build / Publish
        - task: ComponentGovernanceComponentDetection@0
          displayName: Component Governance scan

      - job: Linux
        container: LinuxContainer
        pool:
          name: $(PoolProvider)
          demands: ImageOverride -equals $(LinuxAmd64BuildImage)
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              # Test signing is not supported on Linux
              _SignType: none
            Build_Release:
              _BuildConfig: Release
              # Test signing is not supported on Linux
              _SignType: none
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            --sign
          displayName: Unix Build / Publish
        - task: ComponentGovernanceComponentDetection@0
          displayName: Component Governance scan

      - job: MacOS
        pool:
          vmImage: $(MacOSBuildImage)
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              # Test signing is not supported on macOS
              _SignType: none
            Build_Release:
              _BuildConfig: Release
              # Test signing is not supported on macOS
              _SignType: none
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            --sign
          displayName: Unix Build / Publish
        - task: ComponentGovernanceComponentDetection@0
          displayName: Component Governance scan
