variables:
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - name: PoolProvider
      value: NetCore-Public
      readonly: true
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - name: PoolProvider
      value: NetCore1ESPool-Internal
      readonly: true

trigger: none

pr:
  branches:
    include:
    - main

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-amd64

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      enableTelemetry: true
      jobs:
      - job: Windows_NT
        pool:
          name: $(PoolProvider) # This is a queue-time parameter; Public default is NetCore-Public; Internal default is NetCore1ESPool-Internal
          demands: ImageOverride -equals windows.vs2022.amd64.open

        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              # PRs or external builds are not signed.
              _SignType: test
            Build_Debug:
              _BuildConfig: Debug
              _SignType: test
        preSteps:
        - checkout: self
          clean: true
        steps:
        # Use utility script to run script command dependent on agent OS.
        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig)
            -prepareMachine
          displayName: Windows Build / Publish
        - task: ComponentGovernanceComponentDetection@0
          displayName: Component Governance scan

      - job: Linux
        container: LinuxContainer
        pool:
          name: $(PoolProvider)  # This is a queue-time parameter; Public default is NetCore-Public; Internal default is NetCore1ESPool-Internal
          demands: ImageOverride -equals Build.Ubuntu.2204.Amd64.Open

        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _SignType: none # Test signing is not supported on Linux and macOS.
            Build_Release:
              _BuildConfig: Release
              _SignType: none # Test signing is not supported on Linux and macOS.
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            --sign
          displayName: Unix Build / Publish
        - task: ComponentGovernanceComponentDetection@0
          displayName: Component Governance scan

      - job: MacOS
        pool:
          vmImage: macos-latest

        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _SignType: none # Test signing is not supported on Linux and macOS.
            Build_Release:
              _BuildConfig: Release
              _SignType: none # Test signing is not supported on Linux and macOS.
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng/common/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            --sign
          displayName: Unix Build / Publish
        - task: ComponentGovernanceComponentDetection@0
          displayName: Component Governance scan
