pr:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - eng/pipelines/dotnet-buildtools-image-builder-pr.yml
    - eng/pipelines/templates/*
    - eng/common/templates/*
    - src/*

trigger: none

variables:
- template: /eng/pipelines/templates/variables/image-builder.yml
  parameters:
    sourceBuildPipelineRunId: $(Build.BuildId)

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: /eng/common/templates/dotnet/base-pipeline-nonprod.yml@self
  parameters:
    sourceBuildPipelineRunId: $(Build.BuildId)
    stagesTemplate: /eng/pipelines/templates/pipelines/dotnet-buildtools-image-builder.yml@self
    stagesTemplateParameters:
      sourceBuildPipelineRunId: $(Build.BuildId)
      versionsRepoRef: VersionsRepo
      isPullRequestValidation: true
