pr: none

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

variables:
- template: /eng/pipelines/templates/variables/eng-validation.yml@self

extends:
  template: /eng/common/templates/1es-unofficial.yml@self
  parameters:
    stages:
    - template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
      parameters:
        noCache: true
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
