pr: none

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

variables:
- template: templates/variables/eng-validation.yml

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    noCache: true
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
