pr:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - src/*

trigger: none

variables:
- template: templates/variables/image-builder.yml

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    noCache: true
