pr: none

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

variables:
- template: /eng/pipelines/templates/variables/eng-validation.yml@self

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
      parameters:
        noCache: true
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
