pr:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - src/*

trigger: none

variables:
- template: /eng/pipelines/templates/variables/image-builder.yml@self

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/common/templates/dotnet/base-pipeline-nonprod.yml@self
  parameters:
    baseTemplate:
      template: /eng/pipelines/templates/pipelines/dotnet-buildtools-image-builder.yml@self
      parameters:
        baseTemplate:


# stages:
# - template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
#   parameters:
#     buildMatrixType: platformVersionedOs
#     noCache: true
#     internalProjectName: ${{ variables.internalProjectName }}
#     publicProjectName: ${{ variables.publicProjectName }}
#     versionsRepoRef: VersionsRepo
