pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

trigger: none

variables:
- template: templates/variables/eng-validation.yml

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    noCache: true
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
