# This pipeline is a work in progress.
# See https://github.com/dotnet/dotnet-docker-internal/issues/8566 for more details.

trigger: none
pr: none

parameters:
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test or publish images that were build in a different pipeline run.
    The default value should be left alone if you want to build new images.
  type: string
  default: $(Build.BuildId)

variables:
- template: /eng/pipelines/templates/variables/image-builder.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
# Uses DockerHub registry creds to avoid rate limiting during CopyBaseImages job
- template: /eng/common/templates/variables/dotnet/secrets-unofficial.yml@self
- name: "publishEolAnnotations"
  value: false
  readonly: true
# Unofficial secrets group has no GitHub token for publishing image info or notifications
- name: "publishImageInfo"
  value: false
  readonly: true
- name: "publishNotificationsEnabled"
  value: false
  readonly: true
# There aren't test/unofficial Kusto tables for build telemetry yet
- name: "ingestKustoImageInfo"
  value: false
  readonly: true
# Always run unofficial pipelines in debug mode
- name: "System.Debug"
  value: true
  readonly: true

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/common/templates/dotnet/base-pipeline-nonprod.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
    baseTemplate:
      template: /eng/pipelines/templates/pipelines/dotnet-buildtools-image-builder.yml@self
      parameters:
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        versionsRepoRef: VersionsRepo
        baseTemplate:
          template: /eng/common/templates/1es.yml@self
