trigger: none
pr: none

parameters:
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test or publish images that were build in a different pipeline run.
    The default value should be left alone if you want to build new images.
  type: string
  default: $(Build.BuildId)

- name: bootstrapImageBuilder
  displayName: >
    Bootstrap ImageBuilder from source. When enabled, ImageBuilder is built from
    the current branch's source code instead of pulling the pre-built image.
    Use this to test ImageBuilder source changes end-to-end.
  type: boolean
  default: false

variables:
- template: /eng/pipelines/templates/variables/image-builder.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
# Uses DockerHub registry creds to avoid rate limiting during CopyBaseImages job
- template: /eng/docker-tools/templates/variables/dotnet/secrets-unofficial.yml@self
- name: "publishEolAnnotations"
  value: false
  readonly: true
# Unofficial secrets group has no GitHub token for publishing image info or notifications
- name: "publishImageInfo"
  value: false
  readonly: true
- name: "publishNotificationsEnabled"
  value: false
  readonly: true
# There aren't test/unofficial Kusto tables for build telemetry yet
- name: "ingestKustoImageInfo"
  value: false
  readonly: true
# Always run unofficial pipelines in debug mode
- name: "System.Debug"
  value: true
  readonly: true

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/docker-tools/templates/1es.yml@self
  parameters:
    reposToExcludeFromScanning:
    - VersionsRepo
    stages:
    - template: /eng/docker-tools/templates/stages/dotnet/publish-config-nonprod.yml@self
      parameters:
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        stagesTemplate: /eng/pipelines/templates/stages/build-test-publish.yml@self
        stagesTemplateParameters:
          sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
          versionsRepoRef: VersionsRepo
          noCache: true
          ${{ if eq(parameters.bootstrapImageBuilder, true) }}:
            customImageBuilderSetupSteps:
            - template: /eng/pipelines/templates/steps/bootstrap-imagebuilder.yml@self
