pr:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - src/*

trigger: none

variables:
- template: templates/variables/image-builder.yml

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    noCache: true
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
