pr: none

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/templates/variables/eng-validation.yml@self

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(internal-mirror.serviceConnectionName)
    - name: $(build.serviceConnectionName)
    - name: $(publish.serviceConnectionName)
    - name: $(kusto.serviceConnectionName)
    - name: $(marStatus.serviceConnectionName)
    stages:
    - template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
      parameters:
        noCache: true
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
