pr:
  branches:
    include:
    - master
    - feature/image-info-schema
  paths:
    include:
    - src/*

trigger: none

jobs:
- template: templates/jobs/build-image-builder.yml
  parameters:
    publishImages: false
