pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

trigger: none

variables:
- template: templates/variables/eng-validation.yml
# Define these as placeholder values to allow string validation to succeed since we don't have the
# variable group with the actual values in public builds.
- name: acr.servicePrincipalTenant
  value: 00000000-0000-0000-0000-000000000000
- name: acr.subscription
  value: 00000000-0000-0000-0000-000000000000

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    noCache: true
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
