pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

trigger: none

variables:
- template: /eng/pipelines/templates/variables/eng-validation.yml@self

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: /eng/common/templates/stages/dotnet/publish-config-nonprod.yml@self
  parameters:
    stagesTemplate: /eng/pipelines/templates/stages/build-test-publish.yml@self
    stagesTemplateParameters:
      noCache: true
      versionsRepoRef: VersionsRepo
      isPullRequestValidation: true
