pr:
  branches:
    include:
    - master
  paths:
    include:
    - eng/*
    - test/*

variables:
- template: templates/variables/eng-validation.yml

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    noCache: true