pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - test/*

trigger: none

variables:
- template: /eng/pipelines/templates/variables/eng-validation.yml@self

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: /eng/common/templates/dotnet/base-pipeline-nonprod.yml@self
  parameters:
    stagesTemplate: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
    stagesTemplateParameters:
      buildMatrixType: platformVersionedOs
      noCache: true
      internalProjectName: ${{ variables.internalProjectName }}
      publicProjectName: ${{ variables.publicProjectName }}
      versionsRepoRef: VersionsRepo
