# Imports an image from a 3rd party registry to the public mirror registry

name: $(Date:yyyyMMdd).$(Rev:r)-${{ replace(replace(parameters.imageName, '/', '_'), ':', '_') }}

trigger: none
pr: none

parameters:
- name: imageName
  displayName: >-
    Name and tag of the image to be imported.
    If the image is from Docker Hub, use <repo>:<tag>.
    If the image is from an official Docker Hub registry, make sure to include the library/ prefix.
    If the image is from another registry, use <registry>/<repo>:<tag>.
  type: string
- name: isDockerHubImage
  displayName: Is the image from Docker Hub?
  type: boolean
  default: true

variables:
- template: /eng/pipelines/templates/variables/common.yml@self
- ${{ if eq(parameters.isDockerHubImage, 'true') }}:
  # Uses DockerHub registry credentials to avoid rate limiting
  - group: Dotnet-Docker-Secrets-Low
  - name: normalizedImageName
    value: ${{ format('docker.io/{0}', parameters.imageName) }}
  - name: extraImportOptions
    value: --username $(dotnet-dockerhub-bot-username) --password $(dotnet-dockerhub-bot-pat-low)
- ${{ else }}:
  - name: normalizedImageName
    value: ${{ parameters.imageName }}
  - name: extraImportOptions
    value: ''

extends:
  template: /eng/docker-tools/templates/1es.yml@self
  parameters:
    stages:
    - stage: Import
      dependsOn: []
      jobs:
      - job: Import
        steps:
        - template: /eng/docker-tools/templates/steps/run-pwsh-with-auth.yml@self
          parameters:
            displayName: Import image
            serviceConnection: $(public-mirror.serviceConnectionName)
            command: >
              az acr import
              --subscription $(public-mirror.subscription)
              --resource-group $(public-mirror.resourceGroup)
              --name $(public-mirror.server)
              --source $(normalizedImageName)
              --image ${{ parameters.imageName }}
              $(extraImportOptions)
