trigger: none
pr: none

schedules:
- cron: "0 0,6,12,18 * * *"
  displayName: Daily build
  branches:
    include:
    - main
  always: true

parameters:
- name: dryRun
  displayName: Dry Run
  type: boolean
  default: false

variables:
- template: /eng/docker-tools/templates/variables/dotnet/common.yml@self
# Uses DockerHub registry creds to avoid rate limiting
- template: /eng/docker-tools/templates/variables/dotnet/secrets.yml@self
- name: mirrorRepoPrefix
  value: ""

extends:
  template: /eng/docker-tools/templates/1es.yml@self
  parameters:
    stages:
    - template: /eng/docker-tools/templates/stages/setup-service-connections.yml@self
      parameters:
        serviceConnections:
        - name: $(public-mirror.serviceConnectionName)
    - stage: MirrorBaseImages
      displayName: Mirror Base Images
      dependsOn: []
      jobs:
      - template: /eng/pipelines/templates/jobs/copy-base-images-public-mirror.yml@self
        parameters:
          name: "Public"
          subscriptionsPath: eng/check-base-image-subscriptions.json
          dryRun: ${{ parameters.dryRun }}
      - template: /eng/pipelines/templates/jobs/copy-base-images-public-mirror.yml@self
        parameters:
          name: "Public_Buildtools"
          subscriptionsPath: eng/check-base-image-subscriptions-buildtools.json
          dryRun: ${{ parameters.dryRun }}
