trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - eng/docker-tools/*
pr: none

variables:
- template: /eng/pipelines/templates/variables/common.yml
# Uses GitHub token to submit pull requests
- template: /eng/docker-tools/templates/variables/dotnet/secrets.yml@self

jobs:
- job: Build
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - script: >
      docker build . -f ./eng/src/file-pusher/Dockerfile -t file-pusher
    displayName: Build File Pusher
  - script: >
      docker run --rm file-pusher
      $(filters)
      ./eng/docker-tools-file-pusher-config.json
      $(dotnetDockerBot.userName)
      $(dotnetDockerBot.email)
      $(BotAccount-dotnet-docker-bot-PAT)
    displayName: Run File Pusher
