trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - eng/common/*
pr: none

variables:
- template: ../common/templates/variables/common.yml

jobs:
- job: Build
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - script: >
      docker build . -f ./eng/file-pusher/Dockerfile -t file-pusher
    displayName: Build File Pusher
  - script: >
      docker run --rm file-pusher
      $(filters)
      ./eng/eng-common-file-pusher-config.json
      $(dotnetDockerBot.userName)
      $(dotnetDockerBot.email)
      $(BotAccount-dotnet-docker-bot-PAT)
    displayName: Run File Pusher
