trigger: none
pr: none

parameters:
- name: containerName
  displayName: Blob Container Name
  type: string
- name: sourceFilePath
  displayName: Source File Path
  type: string
- name: destName
  displayName: Destination Name
  type: string

variables:
- template: /eng/pipelines/templates/variables/common.yml@self

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - stage: UploadFile
      displayName: Upload File
      jobs:
      - job: Execute
        steps:
        - script: >
            az storage blob upload
            --account-name $(dotnetBinaries.accountName)
            --account-key $(dotnetbinaries-accountkey)
            --container-name ${{ parameters.containerName }}
            --file $(Build.SourcesDirectory)/${{ parameters.sourceFilePath }}
            --name ${{ parameters.destName }}
          displayName: Upload File
