parameters:
  publishImages: false

jobs:
- job: Initialize
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - powershell: write-host "##vso[task.setvariable variable=timestamp;isOutput=true]$(Get-Date -Format yyyyMMddHHmmss)"
    displayName: Define Timestamp Variable
    name: GenerateTimestamp
- template: build-image-builder-image.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604
    publishImages: ${{ parameters.publishImages }}
- template: build-image-builder-image.yml
  parameters:
    name: Windows
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: DotNetCore-Docker-Public
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: DotNetCore-Docker
      demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
    publishImages: ${{ parameters.publishImages }}
