parameters:
  jobName: null
  subscriptionsPath: null
  customGetStaleImagesArgs: ""
  publicProjectName: null
  internalProjectName: null

jobs:
- job: ${{ parameters.jobName }}
  pool:
    name: NetCore1ESPool-Internal
    image: 1es-ubuntu-2204
    os: linux
  steps:
  - template: /eng/common/templates/steps/init-docker-linux.yml@self
  - template: /eng/common/templates/steps/copy-base-images.yml@self
    parameters:
      additionalOptions: "--subscriptions-path '${{ parameters.subscriptionsPath }}'"
      publicProjectName: ${{ parameters.publicProjectName }}
      internalProjectName: ${{ parameters.internalProjectName }}
  - script: >
      $(runImageBuilderCmd)
      getStaleImages
      $(dotnetDockerBot.userName)
      $(dotnetDockerBot.email)
      $(BotAccount-dotnet-docker-bot-PAT)
      staleImagePaths
      ${{ parameters.customGetStaleImagesArgs }}
      --subscriptions-path ${{ parameters.subscriptionsPath }}
      --os-type '*'
      --architecture '*'
    displayName: Get Stale Images
    name: GetStaleImages
  - script: >
      $(runImageBuilderCmd)
      queueBuild
      $(System.AccessToken)
      dnceng
      internal
      --git-token '$(BotAccount-dotnet-docker-bot-PAT)'
      --git-owner 'dotnet'
      --git-repo '$(internalGitHubRepo)'
      --subscriptions-path ${{ parameters.subscriptionsPath }}
      --image-paths "$(GetStaleImages.staleImagePaths)"
    displayName: Queue Build for Stale Images
