parameters:
- name: name
  type: string
  default: null
- name: subscriptionsPath
  type: string
  default: null
- name: customInitSteps
  type: stepList
  default: []
- name: dryRun
  type: boolean
  default: false

jobs:
- template: /eng/common/templates/jobs/copy-base-images.yml@self
  parameters:
    name: MirrorBaseImages_${{ parameters.name }}
    pool:
      name: $(default1ESInternalPoolName)
      image: $(default1ESInternalPoolImage)
      os: linux
    acr:
      server: $(public-mirror.server)
      serviceConnection:
        id: $(public-mirror.serviceConnection.id)
        tenantId: $(public-mirror.serviceConnection.tenantId)
        clientId: $(public-mirror.serviceConnection.clientId)
      subscription: $(public-mirror.subscription)
      resourceGroup: $(public-mirror.resourceGroup)
    repoPrefix: $(mirrorRepoPrefix)
    customInitSteps: ${{ parameters.customInitSteps }}
    additionalOptions: '--subscriptions-path ${{ parameters.subscriptionsPath }}'
    forceDryRun: ${{ parameters.dryRun }}
