parameters:
- name: name
  type: string
  default: null
- name: subscriptionsPath
  type: string
- name: publishConfig
  type: object
- name: customInitSteps
  type: stepList
  default: []
- name: dryRun
  type: boolean
  default: false

jobs:
- template: /eng/docker-tools/templates/jobs/copy-base-images.yml@self
  parameters:
    name: MirrorBaseImages_${{ parameters.name }}
    pool:
      name: $(default1ESInternalPoolName)
      image: $(default1ESInternalPoolImage)
      os: linux
    publishConfig: ${{ parameters.publishConfig }}
    acr: ${{ parameters.publishConfig.PublicMirrorRegistry }}
    repoPrefix: $(mirrorRepoPrefix)
    customInitSteps: ${{ parameters.customInitSteps }}
    additionalOptions: '--subscriptions-path ${{ parameters.subscriptionsPath }}'
    forceDryRun: ${{ parameters.dryRun }}
