parameters:
  buildMatrixType: platformDependencyGraph
  testMatrixType: platformVersionedOs
  buildMatrixCustomBuildLegGroupArgs: ""
  testMatrixCustomBuildLegGroupArgs: ""
  customCopyBaseImagesInitSteps: []
  customGenerateMatrixInitSteps: []
  customBuildInitSteps: []
  customTestInitSteps: []
  customPublishInitSteps: []
  customPublishVariables: []

  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60
  windowsAmdBuildJobTimeout: 60

  linuxAmdTestJobTimeout: 60
  linuxArmTestJobTimeout: 60
  windowsAmdTestJobTimeout: 60

  noCache: false

  internalProjectName: null
  publicProjectName: null

  internalVersionsRepoRef: null
  publicVersionsRepoRef: null

  isInternalServicingValidation: false

  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  linuxArm32Pool:
    vmImage: $(defaultLinuxArm32PoolImage)
  linuxArm64Pool:
    vmImage: $(defaultLinuxArm64PoolImage)
  windows2016Pool:
    vmImage: $(defaultWindows2016PoolImage)
  windows1809Pool:
    vmImage: $(defaultWindows1809PoolImage)
  windows2022Pool:
    vmImage: $(defaultWindows2022PoolImage)
  windows2025Pool:
    vmImage: $(defaultWindows2025PoolImage)


stages:

################################################################################
# Build and test images
################################################################################
- template: /eng/common/templates/stages/build-and-test.yml@self
  parameters:
    buildMatrixType: ${{ parameters.buildMatrixType }}
    testMatrixType: ${{ parameters.testMatrixType }}
    buildMatrixCustomBuildLegGroupArgs: ${{ parameters.buildMatrixCustomBuildLegGroupArgs }}
    testMatrixCustomBuildLegGroupArgs: ${{ parameters.testMatrixCustomBuildLegGroupArgs }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
    customGenerateMatrixInitSteps: ${{ parameters.customGenerateMatrixInitSteps }}
    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customTestInitSteps: ${{ parameters.customTestInitSteps }}
    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}
    windowsAmdBuildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
    linuxAmdTestJobTimeout: ${{ parameters.linuxAmdTestJobTimeout }}
    linuxArmTestJobTimeout: ${{ parameters.linuxArmTestJobTimeout }}
    windowsAmdTestJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    internalVersionsRepoRef: ${{ parameters.internalVersionsRepoRef }}
    publicVersionsRepoRef: ${{ parameters.publicVersionsRepoRef }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
    linuxArm32Pool: ${{ parameters.linuxArm32Pool }}
    linuxArm64Pool: ${{ parameters.linuxArm64Pool }}
    windows2016Pool: ${{ parameters.windows2016Pool }}
    windows1809Pool: ${{ parameters.windows1809Pool }}
    windows2022Pool: ${{ parameters.windows2022Pool }}
    windows2025Pool: ${{ parameters.windows2025Pool }}

################################################################################
# Publish Images
################################################################################
- template: /eng/common/templates/stages/publish.yml@self
  parameters:
    customPublishInitSteps: ${{ parameters.customPublishInitSteps }}
    customPublishVariables: ${{ parameters.customPublishVariables }}
    internalProjectName: ${{ parameters.internalProjectName }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    pool: ${{ parameters.linuxAmd64Pool }}
