# This pipeline template injects the publish config for the dotnet-docker
# non-production environment.

parameters:
- name: sourceBuildPipelineRunId
  type: string
  default: $(Build.BuildId)

# This template will have the publishConfig passed to it as a parameter.
- name: stagesTemplate
  type: string
- name: stagesTemplateParameters
  type: object
  default: {}

stages:
- template: ${{ parameters.stagesTemplate }}
  parameters:
    ${{ insert }}: ${{ parameters.stagesTemplateParameters }}

    internalProjectName: "internal"
    publicProjectName: "public"

    publishConfig:
      internalMirrorAcr:
        server: $(acr-staging-test.server)
        repoPrefix: $(mirrorRepoPrefix)
        resourceGroup: $(testResourceGroup)
        subscription: $(testSubscription)
        serviceConnection:
          name: $(internal-mirror-test.serviceConnectionName)
          id: $(internal-mirror-test.serviceConnection.id)
          clientId: $(internal-mirror-test.serviceConnection.clientId)
          tenantId: $(testTenant)

      publicMirrorAcr:
        server: $(public-mirror.server)

      buildAcr:
        server: $(acr-staging-test.server)
        resourceGroup: $(testResourceGroup)
        subscription: $(testSubscription)
        repoPrefix: "build/${{ parameters.sourceBuildPipelineRunId }}/"
        serviceConnection:
          name: $(build-test.serviceConnectionName)
          id: $(build-test.serviceConnection.id)
          clientId: $(build-test.serviceConnection.clientId)
          tenantId: $(testTenant)

      testServiceConnection:
        name: $(test-nonprod.serviceConnectionName)
        id: $(test-nonprod.serviceConnection.id)
        clientId: $(test-nonprod.serviceConnection.clientId)
        tenantId: $(testTenant)

      publishAcr:
        server: $(acr-test.server)
        resourceGroup: $(testResourceGroup)
        subscription: $(testSubscription)
        repoPrefix: "public/"
        serviceConnection:
          name: $(publish-test.serviceConnectionName)
          id: $(publish-test.serviceConnection.id)
          clientId: $(publish-test.serviceConnection.clientId)
          tenantId: $(testTenant)
