# A wrapper template around the common build-test-publish-repo template with settings
# specific to the .NET team's infrastructure.

parameters:
  noCache: false
  isInternalServicingValidation: false

  internalProjectName: null
  publicProjectName: null

  buildMatrixCustomBuildLegGroupArgs: ""
  testMatrixCustomBuildLegGroupArgs: ""

  customCopyBaseImagesInitSteps: []
  customGenerateMatrixInitSteps: []
  customBuildInitSteps: []
  customTestInitSteps: []
  customPublishInitSteps: []

  windowsAmdBuildJobTimeout: 60
  windowsAmdTestJobTimeout: 60
  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60

  linuxAmd64Pool: ""

  buildMatrixType: platformDependencyGraph
  testMatrixType: platformVersionedOs


stages:

- template: /eng/common/templates/stages/build-and-test.yml@self
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    customGenerateMatrixInitSteps: ${{ parameters.customGenerateMatrixInitSteps }}
    buildMatrixCustomBuildLegGroupArgs: ${{ parameters.buildMatrixCustomBuildLegGroupArgs }}
    testMatrixCustomBuildLegGroupArgs: ${{ parameters.testMatrixCustomBuildLegGroupArgs }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customTestInitSteps: ${{ parameters.customTestInitSteps }}
    customPublishInitSteps: ${{ parameters.customPublishInitSteps }}
    windowsAmdBuildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
    windowsAmdTestJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}
    buildMatrixType: ${{ parameters.buildMatrixType }}
    testMatrixType: ${{ parameters.testMatrixType }}

- template: /eng/common/templates/stages/publish.yml@self
  parameters:
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    pool: ${{ parameters.pool }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    customPublishInitSteps: ${{ parameters.customPublishInitSteps }}
