# This template injects stages for building and publishing ImageBuilder.

parameters:
- name: publishConfig
  type: object
  default: null

- name: internalProjectName
  type: string

- name: publicProjectName
  type: string

- name: sourceBuildPipelineRunId
  type: string
  default: $(Build.BuildId)

- name: versionsRepoRef
  type: string
  default: ""

- name: isPullRequestValidation
  type: boolean
  default: false

stages:
- ${{ if not(parameters.isPullRequestValidation) }}:
  - template: /eng/common/templates/stages/setup-service-connections.yml@self
    parameters:
      serviceConnections:
      - name: ${{ parameters.publishConfig.internalMirrorAcr.serviceConnection.name }}
      - name: ${{ parameters.publishConfig.buildAcr.serviceConnection.name }}
      - name: ${{ parameters.publishConfig.publishAcr.serviceConnection.name }}

- template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    noCache: true
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
    ${{ if ne(parameters.versionsRepoRef, '') }}:
      versionsRepoRef: ${{ parameters.versionsRepoRef }}
    publishConfig: ${{ parameters.publishConfig }}
