# Use this Dockerfile to create an ImageBuilder image
ARG IMAGE
FROM $IMAGE

# Keep this path in sync with $(containerBuildRepoRoot) in
# eng/docker-tools/templates/steps/init-matrix-build-publish.yml
WORKDIR /repo
COPY . .
