# Build, test, and publish images based on the publishConfig parameter and what
# variables are defined.

parameters:
- name: publishConfig
  type: object

- name: internalProjectName
  type: string

- name: publicProjectName
  type: string

- name: sourceBuildPipelineRunId
  type: string
  default: $(Build.BuildId)

- name: versionsRepoRef
  type: string
  default: ""

- name: noCache
  type: boolean
  default: false

# Additional service connections needed by this pipeline that are not included
# in the publishConfig.
- name: additionalServiceConnections
  type: object
  default: []

stages:
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /eng/docker-tools/templates/stages/setup-service-connections.yml@self
    parameters:
      serviceConnections:
      - name: ${{ parameters.publishConfig.internalMirrorAcr.serviceConnection.name }}
      - name: ${{ parameters.publishConfig.buildAcr.serviceConnection.name }}
      - name: ${{ parameters.publishConfig.publishAcr.serviceConnection.name }}
      - ${{ each serviceConnection in parameters.additionalServiceConnections }}:
        - name: ${{ serviceConnection.name }}

- template: /eng/docker-tools/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
    publishConfig: ${{ parameters.publishConfig }}
    ${{ if ne(parameters.versionsRepoRef, '') }}:
      versionsRepoRef: ${{ parameters.versionsRepoRef }}
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      buildMatrixType: platformVersionedOs
