# Build, test, and publish images based on the publishConfig parameter and what
# variables are defined.

parameters:
- name: publishConfig
  type: object

- name: internalProjectName
  type: string

- name: publicProjectName
  type: string

- name: sourceBuildPipelineRunId
  type: string
  default: $(Build.BuildId)

- name: versionsRepoRef
  type: string
  default: ""

- name: noCache
  type: boolean
  default: false

# When provided, ImageBuilder will not be pulled from MCR at the start of each
# job and these steps will be run instead.
- name: customInitSteps
  type: stepList
  default: []

# Additional service connections needed by this pipeline that are not included
# in the publishConfig.
- name: additionalServiceConnections
  type: object
  default: []

stages:
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /eng/docker-tools/templates/stages/setup-service-connections.yml@self
    parameters:
      publishConfig: ${{ parameters.publishConfig }}
      usesRegistries:
        - ${{ parameters.publishConfig.BuildRegistry.server }}
        - ${{ parameters.publishConfig.PublishRegistry.server }}
        - ${{ parameters.publishConfig.InternalMirrorRegistry.server }}
      serviceConnections: ${{ parameters.additionalServiceConnections }}

- template: /eng/docker-tools/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
    publishConfig: ${{ parameters.publishConfig }}
    customInitSteps: ${{ parameters.customInitSteps }}
    ${{ if ne(parameters.versionsRepoRef, '') }}:
      versionsRepoRef: ${{ parameters.versionsRepoRef }}
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      buildMatrixType: platformVersionedOs
