# This stage template checks for updates to base images for multiple repos, and
# queues build jobs if any images are out-of-date.

parameters:
# Publishing configuration containing registry and service connection settings.
# Schema is defined in src/ImageBuilder/Configuration/PublishConfiguration.cs.
- name: publishConfig
  type: object
# The name of the internal Azure DevOps project (e.g., "internal").
- name: internalProjectName
  type: string
# The name of the public Azure DevOps project (e.g., "public").
- name: publicProjectName
  type: string

stages:
- template: /eng/docker-tools/templates/stages/setup-service-connections.yml@self
  parameters:
    serviceConnections:
    - name: ${{ parameters.publishConfig.InternalMirrorRegistry.serviceConnection.name }}
    # Workaround for https://github.com/dotnet/docker-tools/issues/1914:
    # "ACR authentication can fail when using two different service connections for the same ACR"
    # Both InternalMirrorRegistry and BuildRegistry point to the same ACR, but
    # have different service connections. BuildRegistry is listed first in the
    # publish config, so we have to declare it here since it will be used for
    # ACR authentication.
    - name: ${{ parameters.publishConfig.BuildRegistry.serviceConnection.name }}

- stage: CheckBaseImages
  displayName: Check Base Images
  dependsOn: []
  jobs:

  - template: /eng/pipelines/templates/jobs/check-base-image-updates.yml@self
    parameters:
      jobName: CheckBaseImages
      subscriptionsPath: eng/check-base-image-subscriptions.json
      publicProjectName: ${{ parameters.publicProjectName }}
      internalProjectName: ${{ parameters.internalProjectName }}
      publishConfig: ${{ parameters.publishConfig }}

  - template: /eng/pipelines/templates/jobs/check-base-image-updates.yml@self
    parameters:
      jobName: CheckBaseImages_BuildTools
      subscriptionsPath: eng/check-base-image-subscriptions-buildtools.json
      customGetStaleImagesArgs: --base-override-regex '^((centos|debian|ubuntu):.+)' --base-override-sub '$(overrideRegistry)/$1'
      publicProjectName: ${{ parameters.publicProjectName }}
      internalProjectName: ${{ parameters.internalProjectName }}
      publishConfig: ${{ parameters.publishConfig }}
