parameters:
- name: publishConfig
  type: object
  default: null
- name: enableDryRun
  type: boolean
  default: false
- name: repo
  type: string
  default: null
- name: action
  type: string
  default: null
- name: age
  type: int
  default: 0

stages:
- stage: Execute
  jobs:
  - job: Clean
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    variables:
      dryRunArg: ${{ iif(parameters.enableDryRun, '--dry-run', '') }}
    steps:
    - template: /eng/common/templates/steps/init-docker-linux.yml@self
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        internalProjectName: internal
        repo: ${{ parameters.repo }}
        acr: ${{ parameters.publishConfig.buildAcr }}
        action: ${{ parameters.action }}
        age: ${{ parameters.age }}
