parameters:
- name: publishConfig
  type: object
  default: null
- name: enableDryRun
  type: boolean
  default: false
- name: internalProjectName
  type: string
  default: null
- name: publicProjectName
  type: string
  default: null

stages:
- stage: Execute
  dependsOn: []
  jobs:     
  - job: Clean
    variables:
      dryRunArg: ${{ iif(parameters.enableDryRun, '--dry-run', '') }}
    steps:
    - template: /eng/common/templates/steps/init-docker-linux.yml@self
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "build-staging/*"
        acr: ${{ parameters.publishConfig.buildAcr }}
        action: delete
        age: 15
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "public/dotnet/*"
        acr: ${{ parameters.publishConfig.publishAcr }}
        action: pruneEol
        age: 15
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "test/*"
        acr: ${{ parameters.publishConfig.publishAcr }}
        action: pruneAll
        age: 7
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "public/dotnet-buildtools/*"
        acr: ${{ parameters.publishConfig.publishAcr }}
        action: pruneEol
        age: 15
        customArgs: $(excludedBuildToolsPrereqsImagesArgs)
    # Disabled due to https://github.com/dotnet/docker-tools/issues/797
    # - template: ../common/templates/steps/clean-acr-images.yml
    #   parameters:
    #     publishConfig: ${{ parameters.publishConfig }}
    #     repo: "mirror/*"
    #     acr: ${{ parameters.publishConfig.buildAcr }}
    #     action: pruneDangling
    #     age: 0
  - job: Annotations
    variables:
      dryRunArg: ${{ iif(parameters.enableDryRun, '--dry-run', '') }}
    steps:
    - template: /eng/common/templates/steps/init-docker-linux.yml@self
    - script: mkdir -p $(Build.ArtifactStagingDirectory)/eol-annotation-data
      displayName: Create EOL Annotation Data Directory
    - template: /eng/pipelines/templates/steps/set-eol-annotations.yml@self
      parameters:
        acr: ${{ parameters.publishConfig.buildAcr }}
    - template: /eng/pipelines/templates/steps/set-eol-annotations.yml@self
      parameters:
        acr: ${{ parameters.publishConfig.publicMirrorAcr }}
    - template: /eng/common/templates/steps/publish-artifact.yml@self
      parameters:
        path: $(Build.ArtifactStagingDirectory)/eol-annotation-data
        artifactName: eol-annotation-data-$(System.JobAttempt)
        displayName: Publish EOL Annotation Data Artifact
        internalProjectName: internal
        publicProjectName: public
