parameters:
  publishConfig: null
  internalProjectName: "internal"

stages:
- stage: Execute
  dependsOn: []
  jobs:     
  - job: Clean
    steps:
    - template: /eng/common/templates/steps/init-docker-linux.yml@self
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "build-staging/*"
        acr: ${{ parameters.publishConfig.buildAcr }}
        action: delete
        age: 15
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "public/dotnet/*"
        acr: ${{ parameters.publishConfig.publishAcr }}
        action: pruneEol
        age: 15
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "test/*"
        acr: ${{ parameters.publishConfig.publishAcr }}
        action: pruneAll
        age: 7
    - template: /eng/common/templates/steps/clean-acr-images.yml@self
      parameters:
        publishConfig: ${{ parameters.publishConfig }}
        internalProjectName: ${{ parameters.internalProjectName }}
        repo: "public/dotnet-buildtools/*"
        acr: ${{ parameters.publishConfig.publishAcr }}
        action: pruneEol
        age: 15
        customArgs: $(excludedBuildToolsPrereqsImagesArgs)
    # Disabled due to https://github.com/dotnet/docker-tools/issues/797
    # - template: ../common/templates/steps/clean-acr-images.yml
    #   parameters:
    #     publishConfig: ${{ parameters.publishConfig }}
    #     repo: "mirror/*"
    #     acr: ${{ parameters.publishConfig.buildAcr }}
    #     action: pruneDangling
    #     age: 0
